### ISSUE TITLE
Task: evaluate externalized ids prototype for high-priority use cases.

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#10]

**Comment by paulmartel** [comment]
1.     connecting the bodies/shapes from the physics engine with user defined information (like meshes, color, etc.)
See the updated Spheres example.
2.     being able to select bodies with mouse
Seems like this would just customized Ray/Shape collision detectors to calculate which shape if any has the closest collision along a ray ( a pair of Vec3's for world position and world normal ) projected "from the camera" through the clicked point on the view screen.
3.     being able to interact with certain bodies
Any kind of meaningful interaction will involve replacing immutable bodies in a copied world (and possibly immutable shapes within copied bodies. It seems to make sense that these replacements would keep take over the ID associations of their originals, so any exposed IDs would remain valid.
4.     being able to detect collisions events (when a certain body has collided with another body)
This seems like a variation of your code to expose all contacts (for diagnostic display) with added filtering for specific objects and possibly for new vs. previously reported/handled contacts.
5.     being able to query specific information from the engine, e.g. where is a certain body located now
Mapping IDs back through the world to access current state seems not very difficult.

Maybe we should prioritize these and split them out as separate issues/tasks.

**Comment by w0rm** [comment]
@paulmartel I think I've already mentioned this, but what do you think about only exposing body ids? The shapes can be pretransformed at the time of addition to a body. From the user perspective, meshes can be generated for the whole bodies, meaning less meshes and less WebGL draw calls.

**Comment by w0rm** [comment]
I decided against `id` in the new api #43, because ids make api very difficult. The `Body data` approach lets users decide what they want as `data`. This can be meshes  https://github.com/w0rm/elm-physics/blob/master/examples/Common/Bodies.elm that really simplified the demo setup, or even ids if users wish to link external information.
