### ISSUE TITLE
Samples need other/more dependecies

### ISSUE THREAD

**Issue by PixelPartner** [w0rm/elm-physics#106]
My assumption was to create a fresh elm project, install `elm-physics`, download an example to src/ (ie `Animate.elm`) and run `make`. That didn't work for me!
And the imported module names do not intuitively point to the needed packages, or what to move from indirect to direct.

I suggest to add a `README.md` to the `examples` folder that specifies their dependencies.

**Comment by w0rm** [comment]
@PixelPartner this is a good idea! My current plan is to rewrite all examples to be self sufficient and rendered with elm-3d-scene instead of raw WebGL. Then I can also put together a readme with what needs to be installed, or refer to elm.json in the examples folder.
