### ISSUE TITLE
Feature: Diagnostic display of normals and edges

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#11]
Provide example UI for more dynamic control.
Possibly refactor into fold-like generic functions with "visitor function" arguments to reduce duplication of production code.

**Comment by w0rm** [comment]
I'm also thinking about moving these function into the `Physics.Debug` submodule in the public api.

**Comment by w0rm** [comment]
Another idea here is to cache the collision points, so that we don't run the narrow phase twice

**Comment by w0rm** [comment]
I think this may be closed via https://github.com/w0rm/elm-physics/pull/18, I will keep my suggestions in mind for the future.
