### ISSUE TITLE
Style (performance?) improvement: refactor ConvexPolyhedron to use patterns and idioms.

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#14]
Convert non-shortcutting recursive functions to use folds instead
-- makes them more idiomatic and so easier to understand, and more efficient.

Convert short-cutting recursive functions (and those that SHOULD be short-cutting for better performance) to use visitor functions and generic recursion functions in the style of fold functions like

listRecurseUntil : (b -> Bool) -> (a -> b -> b) -> b -> List a -> b
listRecurseUntil doneFn fn seed list =

to isolate reusable recursive navigation from each function's node-specific processing.

Export fold-like generic functions that use function-typed arguments and dependent typing to reduce package dependencies. I.e. one exported fold-based function that takes a "visitor function" argument and a dependently typed acc argument and return value could replace several specialized exported functions that walk the same structure for different purposes.

Propagate this visitor pattern up the API chain to bypass the building, concatenating, mapping of temporary result lists.

**Comment by w0rm** [comment]
I am not sure if this would perform faster than a tail call optimized recursion. Adding extra callbacks could potentially make it slower. A good thing is that there is https://github.com/BrianHicks/elm-benchmark that we can utilize to measure such improvements.

**Comment by paulmartel** [comment]
I agree that extra callbacks could add a little to the cost, but I'll wait to see benchmarks before trying to predict how much.  The potential win compared to a fold without shortcuts could be much more significant. 

I imagine that a hard-coded custom recursive function with shortcuts might usually have the absolute best performance, at least by a little. It may become a hard question of how much readability/maintainability one is willing to trade for how much/little extra performance.

I think that listRecurseUntil itself might qualify for tail recursion optimization, if available.
Do you know whether elm detects and optimizes tail recursions? I've been assuming "not".

**Comment by w0rm** [comment]
Updated convex code to use `listRecurseUntil` and `listRingFoldStaggeredPairs`.
