### ISSUE TITLE
Optimization: cache connectedFaces for each ConvexPolyhedron face.

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#15]
Calculate up front and cache an (Array (List Int)) of the connectedFaces for each face to prevent n-squared cycling in collision detection. BTW, I slightly prefer the term "adjacent face" to "connected face".

**Comment by w0rm** [comment]
This could be done together with #16 to not require an additional array.

**Comment by w0rm** [comment]
Closed via #22
