### ISSUE TITLE
Style (Optimization?): replace ConvexPolyhedron's parallel Array members with one Array of records.

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#16]
The elements of the current arrays: faces and normals (and soon connectedFaces) could become the attributes of the record elements in the one Array. 

This would reduce clumsy parallel array indexing with its requisite increments and Maybe-based failure handling, superfluous for same-sized Arrays.

**Comment by w0rm** [comment]
Yeah, I've been thinking of this too. This would simplify the collision code and improve the performance as we have to make less array lookups.

**Comment by w0rm** [comment]
Closed via #22
