### ISSUE TITLE
Task: Add NarrowPhase.elm tests

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#26]
At a minimum, the series of addSphereConvexContacts calls in benchmarks/NarrowPhase.elm should be tested to ensure that the benchmarked cases are set up correctly and are getting expected results.

Tests should be in place before any attempt to tune addSphereConvexContacts to guard against regression.

**Comment by w0rm** [comment]
@paulmartel what do you think of creating the `NarrowPhase` subfolder and moving all `ShapeAShapeB.elm` collision functions there?

**Comment by paulmartel** [comment]
We should probably do something like this going forward to keep NarrowPhase.elm from growing on the order of n^2 as we add shapes. I don't know that it's worth applying this convention retroactively to existing shapes.  It would make the most sense to have a separate ShapeAShapeB module when the implementation depended on lots of implementation details of both shapes. When ShapeA is relatively simple like a Plane or even a Sphere I don't see a great deal of harm in the current approach of keeping the collision code in NarrowPhase.elm or in ShapeB.elm.

**Comment by paulmartel** [comment]
There's enough testing now to have confidence that the benchmark results will be valid.
