### ISSUE TITLE
Task: reduce code duplication between benchmarks and tests.

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#27]
There should be a top-level directory for functions that we would rather not have to duplicate between the benchmarks and the tests for a given library function. At a minimum, the directory could contain the definitions of any shared sample data like definitions of useful hulls for NarrowPhase and ConvexPolyhedron testing/benchmarking. At the other extreme, it could contain the definitions of entire test cases or series of test cases -- all that would be left to do in the benchmarks and tests modules, respectively, would be to wrap them in Benchmark boilerplate and to wrap them in Test boilerplate adding their expected result values. Actually, for the sake of keeping things in sync, it would probably make sense for the expected result values to be defined in the common code alongside each test case, even though they would only be useful in tests and not in benchmarks.

Some of this common code could also be useful in constructing example demos.

"sampleData" or "commonData" would be a clear name if we were limiting ourselves to sample data initialization.
Would "sampleCalls" or "commonCalls" be a better name if the intent were more ambitious?

**Comment by w0rm** [comment]
Closed via #28
