### ISSUE TITLE
Add ray-body collision detection to enable future mouse support.

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#32]
Given a ray (world origin point and normal), we need to be able to return details like BodyId, (Body?,) contactPoint, and worldTransform of the nearest collision to the ray's origin along its normal.

It's not clear to me whether this would benefit from being implemented as a Ray Shape -- I suspect not?

**Comment by w0rm** [comment]
Getting some promising results:

![raycast](https://user-images.githubusercontent.com/43472/56467761-5e493600-6423-11e9-8c44-12d96a18f6df.gif)
![raycast-convex](https://user-images.githubusercontent.com/43472/56467762-5f7a6300-6423-11e9-83e5-aa70e5505c1c.gif)
