### ISSUE TITLE
Task: benchmark convex/convex collisions.

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#35]
Benchmarks are needed to motivate and inform and monitor the possible changes described in issue #14 and possibly other future rework.

**Comment by w0rm** [comment]
I've taken a slightly different approach to measuring performance. Elm benchmark is not suitable for macro-benchmarks, so what I did was set up [a scene with 64 cubes](https://unsoundscapes.com/elm-physics/examples/boxes/) and used that to check FPS and use the JavaScript profiler to identify performance bottlenecks. I was able to improve it quite a bit.
