### ISSUE TITLE
Does Physics.Constraint.pointToPoint constrain relative rotation?

### ISSUE THREAD

**Issue by MartinSStewart** [w0rm/elm-physics#74]
Reading the documentation for `Physics.Constraint.pointToPoint` it isn't clear to me if it behaves like a weld joint or a ball joint. I'm guessing the two objects can freely rotate (unless they collide with eachother) but maybe the documentation could be explicit about this behavior?

**Comment by w0rm** [comment]
@MartinSStewart your guess is correct, it only locks two points, but doesn't lock the rotation, so that two objects can freely rotate.
